// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Header: typeof import('./src/components/Header.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Meun: typeof import('./src/components/Meun.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    SubMenu: typeof import('./src/components/SubMenu.vue')['default']
    SubMenuItem: typeof import('./src/components/SubMenuItem.vue')['default']
  }
}

export {}
